config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'enroll', to: 'student_courses#create'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, :name, :description, presence: true, length: { minimum: 3 }
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 3 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:notice] = 'Você precisa estar logado para acessar esta página'
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user, only: [:index]
  def index
    @courses = Course.all
  end

  def new; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user, only: [:about]
  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: %i[new create]
  def new; end

  def create
    student = Student.find_by(email: params[:sessions][:email])
    if student && student.authenticate(params[:sessions][:password])
      session[:student_id] = student.id
      flash[:notice] = 'Estudante logado com sucesso'
      redirect_to student
    else
      flash.now[:notice] = 'Login ou senha inválidos!'
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = 'Deslogado com sucesso!'
    redirect_to root_path
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    if current_user.courses.include?(course_to_add)
      flash[:notice] = 'Houve algum erro na sua inscrição'
      redirect_to root_path
    else
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = "Inscrito com sucesso no curso #{course_to_add.name}"
      redirect_to current_user
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: %i[new create]
  before_action :set_student, only: %i[show edit update]
  before_action :require_same_user, only: %i[edit update]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def show; end

  def edit; end

  def update
    if @student.update(student_params)
      flash[:notice] = 'Dados atualizados com sucesso!'
      redirect_to @student
    else
      render 'edit'
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'Estudante criado com sucesso!'
      redirect_to @student
    else
      render 'new'
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmations)
  end

  def require_same_user
    if current_user != @student
      flash[:notice] = 'Você só pode editar seu proprio perfil'
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if logged_in?
      link_to 'Logout', logout_path, method: :delete
    else
      link_to 'Login', login_path
    end
  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Lista de cursos</h3>
  </div>
</div>
<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6 hoverable">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Codigo: <%= course.short_name %></span>
          <p>Nome: <%= course.name %></p>
          <p>Descrição: <%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !current_user.courses.include?(course)%>
            <%= link_to "Inscreva-se", enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <a href="#">+Info</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>new page</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Universidade Tech</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Ajuda?</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Informações</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contato</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2021 Universidade Tech
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key,msg| %>
  <div class="row card-top "  id="fade-target">
    <div class="col s12 m12 l12 ">
      <div class="card-panel red lighten-2">
        <span class="white-text">
          <%= msg %>
        </span>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
      <li> <%= link_to "Perfil", current_user %></li>
    <% end %>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <li> <%= link_to "Ver Perfil", current_user %> </li>
  </ul>
  <ul id="mobile-demo" class="sidenav">
    <li><%= link_to "Cursos", root_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Estudantes", students_path%></li>
    <% end %>
    <li><a class="dropdown-trigger" data-target="dropdown2">Conta<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to root_path, class: "brand-logo right" do %>
          <i class="material-icons">important_devices</i>
          Tech
        <% end %>
        <a data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="left hide-on-med-and-down">
          <li><%= link_to "Cursos", root_path%></li>
          <% if logged_in? %>
            <li><%= link_to "Estudantes", students_path%></li>
          <% else %>
            <li><%= link_to "Criar Conta", new_student_path %></li>
          <% end %>
          <li><a class="dropdown-trigger"  data-target="dropdown1">Conta<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Universidade Tech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container" >
    <div class="row card-top">
      <div class="col s12 m12 l12 ">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <h5>Ocorreram os seguintes erros:</h5>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
  <%= form_for(@student, html: {class: "col s12"}) do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :name, placeholder: "Entre com seu nome completo", autofocus: true %>
      <%= f.label :name, "Nome" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.email_field :email, placeholder: "Entre com seu email" %>
      <%= f.label :email, class: "active" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.password_field :password, placeholder: "Escolha uma senha" %>
      <%= f.label :password, "Senha", class: "active" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.password_field :password_confirmation, placeholder: "Confirme sua senha" %>
      <%= f.label :password_confirmation, "Confirmar Senha", class: "active" %>
    </div>
  </div>
  <%= f.button btn , class: "grey darken-2 waves-effect waves-light btn " %>
  <!--  (@student.new_record ? "cadastrar" : "salvar") -->
<% end %>

app/views/students/edit.html.erb
<%= render 'shared/errors', obj: @student %>
<div class="container">
  <div class="row center card-top">
    <div class="col s12 m12 l12 ">
      <div class="card-panel">
        <h3 class="center-align">Editar</h3>
        <div class="row">
          <%= render partial: 'form', locals: {btn: "Salvar"} %>
        </div>
      </div>
    </div>
    s
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Lista de Estudantes</h3>
  </div>
</div>
<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6  hoverable">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Nome: <%= student.name %></span>
          <p >Email: <%= student.email %></p>
          <p>lorem ipsum dolor vade mecum</p>
        </div>
        <div class="card-action">
          <%= link_to "Ver Perfil", student %>
          <a href="#">Info</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'shared/errors', obj: @student %>
<div class="container">
  <div class="row center card-top">
    <div class="col s12 m12 l12 ">
      <div class="card-panel">
        <h3 class="center-align">Novo Estudante</h3>
        <div class="row">
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Entre com seu nome completo", autofocus: true %>
                <%= f.label :name, "Nome" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Entre com seu email" %>
                <%= f.label :email %>
              </div>
            </div>
            <button type="submit" class=" grey darken-2 waves-effect waves-light btn">
              <%= f.submit "Cadastrar", class: "white-text" %>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="row card-top">
  <div class="col s6 m6 hoverable">
    <div class="card blue-grey darken-1 ">
      <div class="card-content white-text ">
        <span class="card-title">Nome: <%= @student.name %></span>
        <p >Email: <%= @student.email %></p>
        <p>
          Cursos Inscritos:
          <ul>
            <% if @student.courses.empty? %>
              <li>Nenhum Curso</li>
            <% else %>
              <% @student.courses.each do |course| %>
                <li>
                  <%= course.name %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </p>
      </div>
      <div class="card-action">
        <% if current_user == @student %>
          <%= link_to edit_student_path(@student) do %>
            <i class="tiny material-icons">create</i>
            Editar Perfil
          <% end %>
        <% end %>
        <a href="#">Info</a>
      </div>
    </div>
  </div>
</div>